name: Rotki Development Builds

on:
  schedule:
    - cron: "0 0 * * *"
  push:
    branches:
      - build

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.ref }}
  cancel-in-progress: true

env:
  PYTHON_VERSION: 3.9.13
  NODE_VERSION: 16
  PIP_VERSION: 22.1.2
  PYTHON_MACOS: 11

jobs:
  build-linux:
    name: Build linux binary
    env:
      CI: true
      GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    runs-on: ubuntu-18.04
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Setup python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ env.PYTHON_VERSION }}
          cache: 'pip'
      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: 'npm'
          cache-dependency-path: 'frontend/package-lock.json'
      - name: Cache cypress
        uses: actions/cache@v3
        with:
          path: ~/cache/Cypress
          key: ${{ runner.os }}-node--packaging-${{ hashFiles('frontend/package-lock.json') }}
      - name: Package
        id: packaging
        run: |
          echo "::group::packaging dependencies"
          npm install -g npm@8
          pip3 install --upgrade pip==${{ env.PIP_VERSION }}
          pip3 install packaging requests wheel
          echo "::endgroup::"
          ./package.py --build full
      - name: Upload files
        uses: actions/upload-artifact@v3
        with:
          name: linux-app
          path: |
            dist/*.AppImage
            dist/*.AppImage.sha512
      - name: Notify on failure
        if: ${{ failure() }}
        run: |
          curl --request POST \
            --url ${{ secrets.WEBHOOK }} \
            --header 'Content-Type: application/json' \
            --data '{
          	"content": ":construction_site: **Github Actions:** ${{ github.job }} failed :x: \r\n\r\n  <@&735068019440615516> please have a look at [${{ github.run_id }}](https://github.com/rotki/rotki/actions/runs/${{ github.run_id }}) :cry:"
          }'

  build-macos:
    name: 'Build macOS binary'
    env:
      CI: true
      GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      MACOS_BUILD_ARCH: 'universal2'
      ARCHFLAGS: '-arch arm64 -arch x86_64'
      _PYTHON_HOST_PLATFORM: macosx-10.9-universal2
      MACOSX_DEPLOYMENT_TARGET: 10.9
      CMAKE_OSX_ARCHITECTURES: 'x86_64;arm64'
    environment: macos_sign
    runs-on: macos-11
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Checkout libffi
        uses: actions/checkout@v3
        with:
          repository: libffi/libffi
          path: libffi
          ref: v3.4.2
      - name: Install libffi build tools
        run: brew install autoconf automake libtool pkg-config
      - name: Build universal libbfi (required by coincurve)
        run: |
          brew uninstall --ignore-dependencies libffi
          echo "::group::Autogen"
          ./autogen.sh
          echo "::endgroup::"
          echo "::group::arm64"
          ./configure --host=aarch64-apple-darwin CC='gcc -arch arm64' CXX='g++ -arch arm64'
          make
          mkdir ../ffi
          cp -R aarch64-apple-darwin ../ffi/
          echo "::endgroup::"
          echo "::group::x86_64"
          make clean
          ./configure --host=x86_64-apple-darwin CC='gcc -arch x86_64' CXX='g++ -arch x86_64'
          make
          echo "::endgroup::"
          echo "::group::install"
          lipo -create -output x86_64-apple-darwin/.libs/libffi.8.dylib x86_64-apple-darwin/.libs/libffi.8.dylib ../ffi/aarch64-apple-darwin/.libs/libffi.8.dylib
          lipo -create -output x86_64-apple-darwin/.libs/libffi.a x86_64-apple-darwin/.libs/libffi.a ../ffi/aarch64-apple-darwin/.libs/libffi.a
          lipo -create -output x86_64-apple-darwin/.libs/libffi_convenience.a x86_64-apple-darwin/.libs/libffi_convenience.a ../ffi/aarch64-apple-darwin/.libs/libffi_convenience.a
          lipo -archs x86_64-apple-darwin/.libs/libffi.8.dylib
          make install
          echo "::endgroup::"
        working-directory: libffi
      - name: Cache python pkg
        uses: actions/cache@v3
        with:
          path: ~/python*.pkg
          key: ${{ runner.os }}-python-${{ env.PYTHON_VERSION }}-${{ env.PYTHON_MACOS }}
      - name: Cache python dependencies
        uses: actions/cache@v3
        with:
          path: ~/Library/Caches/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-
      - name: Set up python
        run: packaging/setup-macos-python.sh ${{ env.PYTHON_VERSION }} ${{ env.PYTHON_MACOS }}
      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: 'npm'
          cache-dependency-path: 'frontend/package-lock.json'
      - name: Cache cypress
        uses: actions/cache@v3
        with:
          path: ~/Library/Caches/Cypress
          key: ${{ runner.os }}-node--packaging-${{ hashFiles('frontend/package-lock.json') }}
      - name: Update npm
        run: npm install -g npm@8
      - name: Package
        id: packaging
        run: |
          echo "::group::packaging dependencies"
          pip3 install --upgrade pip==${{ env.PIP_VERSION }}
          pip3 install virtualenv
          python3 -m virtualenv ~/venv
          source ~/venv/bin/activate
          pip3 install packaging requests wheel
          echo "::endgroup::"
          ./package.py --build full
        env:
          CERTIFICATE_OSX_APPLICATION: ${{ secrets.CERTIFICATE_OSX_APPLICATION }}
          CSC_KEY_PASSWORD: ${{ secrets.CERTIFICATE_PASSWORD }}
          IDENTITY: ${{ secrets.IDENTITY }}
          APPLEID: ${{ secrets.APPLEID }}
          APPLEIDPASS: ${{ secrets.APPLEIDPASS }}
      - name: Upload files (arm64)
        uses: actions/upload-artifact@v3
        with:
          name: macos-app-arm64
          path: |
            dist/rotki-darwin_arm64*.dmg
            dist/rotki-darwin_arm64*.dmg.sha512
      - name: Upload files (x86_64)
        uses: actions/upload-artifact@v3
        with:
          name: macos-app-x64
          path: |
            dist/rotki-darwin_x64*.dmg
            dist/rotki-darwin_x64*.dmg.sha512
      - name: Notify on failure
        if: ${{ failure() }}
        run: |
          curl --request POST \
            --url ${{ secrets.WEBHOOK }} \
            --header 'Content-Type: application/json' \
            --data '{
          	"content": ":construction_site: **Github Actions:** ${{ github.job }} failed :x: \r\n\r\n  <@&735068019440615516> please have a look at [${{ github.run_id }}](https://github.com/rotki/rotki/actions/runs/${{ github.run_id }}) :cry:"
          }'
      

  build-windows:
    name: Build windows binary
    env:
      CI: true
      GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      BUILD_DEPENDENCIES: "build-dependencies"
    runs-on: windows-latest
    environment: windows_sign
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Set up python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ env.PYTHON_VERSION }}
          cache: 'pip'
      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: 'npm'
          cache-dependency-path: 'frontend/package-lock.json'
      - name: Cache cypress
        uses: actions/cache@v3
        with:
          path: ~\AppData\Local\Cypress
          key: ${{ runner.os }}-node--packaging-${{ hashFiles('frontend/package-lock.json') }}
      - name: Build rotki
        id: packaging
        env:
          CERTIFICATE_WIN_APPLICATION: ${{ secrets.CERTIFICATE_WIN_APPLICATION }}
          CSC_KEY_PASSWORD: ${{ secrets.CERTIFICATE_PASSWORD }}
        run: |
          echo ::group::"packaging dependencies"
          npm install -g npm@8.12.2 # pinned version because of bug in 8.13.[0,1] check npm/cli#5066
          pip3 install --upgrade pip==${{ env.PIP_VERSION }}
          pip3 install packaging requests wheel
          echo ::endgroup::
          python .\package.py --build full
        shell: powershell
      - name: Upload files
        uses: actions/upload-artifact@v3
        with:
          name: windows-app
          path: |
            dist\rotki-win32*.exe
            dist\rotki-win32*.exe.sha512
      - name: Notify on failure
        if: ${{ failure() }}
        run: |
          $uri="${{ secrets.WEBHOOK }}"
          $body = @{
            "content" = ":construction_site: **Github Actions:** ${{ github.job }} failed :x: <@&735068019440615516> please have a look at [${{ github.run_id }}](https://github.com/rotki/rotki/actions/runs/${{ github.run_id }}) :cry:"
          } | ConvertTo-Json
          Invoke-RestMethod -Method Post -Uri $uri -ContentType "application/json" -Body $body

  build-docker:
    name: Build docker images
    runs-on: ubuntu-18.04
    environment: docker
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
        with:
          platforms: arm64
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USER }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Rotki Version
        id: rotki_version
        run: |
          ROTKI_VERSION=$(cat .bumpversion.cfg | grep 'current_version = ' | sed -n -e 's/current_version = //p')
          POSTFIX=$(if git describe --tags --exact-match "$REVISION" &>/dev/null; then echo ''; else echo '-dev'; fi)
          ROTKI_VERSION=${ROTKI_VERSION}${POSTFIX}-$(date +'%Y.%m.%d')
          echo "::set-output name=version::${ROTKI_VERSION}"
      - name: Build Information
        id: build_information
        run: |
          if [[ "$GITHUB_EVENT_NAME" == 'schedule' ]]; then
            PLATFORMS='linux/amd64,linux/arm64'
            TAG=nightly
          else
            PLATFORMS=linux/amd64
            TAG=dev
          fi
          echo "::set-output name=tag::$TAG"
          echo "::set-output name=platforms::$PLATFORMS"
      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v3
        with:
          context: .
          file: ./Dockerfile
          platforms: ${{ steps.build_information.outputs.platforms }}
          push: true
          tags: rotki/rotki:${{ steps.build_information.outputs.tag }}
          build-args: |
            REVISION=${{ github.sha }}
            ROTKI_VERSION=${{ steps.rotki_version.outputs.version }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
      - name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}
      - name: Notify on failure
        if: ${{ failure() }}
        run: |
          curl --request POST \
            --url ${{ secrets.WEBHOOK }} \
            --header 'Content-Type: application/json' \
            --data '{
          	"content": ":construction_site: **Github Actions:** ${{ github.job }} failed :x: \r\n\r\n  <@&735068019440615516> please have a look at [${{ github.run_id }}](https://github.com/rotki/rotki/actions/runs/${{ github.run_id }}) :cry:"
          }'
